### ISSUE TITLE
Consumer gets stuck on the job complete screen

### ISSUE THREAD

**Issue by dardar8888** [dardar8888/cautious-bassoon#45]
Update in comments.

After a user requests a wash, they are brought to the Service in Progress screen. Currently there is no way to navigate away from the service in progress screen This forces the user to get stuck in the app where if they exit the app and return to it, it till will bring them right to the Service In Progress screen. There is no back button, and the user is left with un-installing the game and re-installing it in order to resume normal use. Even when the service time is at 0, the app won't let you leave the screen.

Screenshot attached.
1. Launch Shyne
2. Login
3. Order a wash
4. Notice that when you are taken to the Service in Progress there is no back button, or any other way to navigate out of the screen
5. Notice that even if you force-quit the game when you re-launch the app, it brings you right back to the service in progress screen

**Comment by jefflanzi** [comment]
Commenty comment

**Comment by jefflanzi** [comment]
I fix this
